services:
  - type: web
    name: client2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    staticPublishPath: "./public"